system_test_mode:
  host: "0.0.0.0"
  port: 49800
  updater:
    type: "deb"
    source_list: "sources.list.d/torigoya-packages.list"
  is_debug_mode: true

release:
  host: "0.0.0.0"
  port: 23432
  updater:
    type: "deb"
    source_list: "sources.list.d/torigoya-packages.list"
  sandbox:
    type: "awaho"
    executable_path: "./_awaho/awaho"
  is_debug_mode: false